name: Lint & Test Code

on:
  push:
    branches:
      - "**"
      - "!main"

jobs:
  yamllint:
    name: Lint & Test Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Setup Requirements
        run: |
          python -m pip install yamllint

      - name: Run Code Linting Test
        run: yamllint .
